# -*- coding: utf-8 -*-
"""LogisticRegression_Binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qW59uHT4k2GMCxVKe5yD6chWyxfkwIkx
"""

import pandas as pd
import numpy as np

df=pd.read_csv('HR_comma_sep.csv')
df.head()
df.isnull().sum()

from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
ordinal_encoder=OrdinalEncoder(categories=[["low","medium","high"]])
onehot_encoder=OneHotEncoder(sparse_output=False)
department_encoded = onehot_encoder.fit_transform(df[['Department']])
# Get feature names for the new columns
feature_names = onehot_encoder.get_feature_names_out(['Department'])
department_df = pd.DataFrame(department_encoded, columns=feature_names, index=df.index)

# Apply OrdinalEncoder
df['salary'] = ordinal_encoder.fit_transform(df[['salary']])

# Drop the original 'Department' column and concatenate the new one-hot encoded columns
df = pd.concat([df.drop('Department', axis=1), department_df], axis=1)

df.head()

# Select numerical columns
numerical_columns = df.select_dtypes(include=['int64', 'float64'])

# Compute correlation matrix
correlation_matrix = numerical_columns.corr(method='pearson')

# Sort correlation with target variable
print(correlation_matrix['left'].sort_values(ascending=False))

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Salary vs Retention (proportion)
salary_retention = pd.crosstab(df['salary'], df['left'], normalize='index')

salary_retention.plot(kind='bar', stacked=True)
plt.title("Salary vs Employee Retention")
plt.ylabel("Proportion")
plt.legend(['Stayed (0)', 'Left (1)'])
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Get all department dummy columns
dept_cols = [col for col in df.columns if col.startswith('Department_')]

# Reconstruct Department column from one-hot encoding
df['Department_reconstructed'] = df[dept_cols].idxmax(axis=1)

# Clean the names (remove 'Department_' prefix)
df['Department_reconstructed'] = df['Department_reconstructed'].str.replace('Department_', '')

# Now perform crosstab
dept_retention = pd.crosstab(df['Department_reconstructed'], df['left'], normalize='index')

# Plot
dept_retention.plot(kind='bar', stacked=True, figsize=(10,5))
plt.title("Department vs Employee Retention")
plt.ylabel("Proportion")
plt.legend(['Stayed (0)', 'Left (1)'])
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pandas as pd
X = df[['satisfaction_level',
        'number_project',
        'average_montly_hours',
        'time_spend_company',
        'promotion_last_5years',
        'salary']]

y = df['left']
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
logic_reg=LogisticRegression()
logic_reg.fit(x_train,y_train)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = logic_reg.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
